const CONFIG = {
    introTitle: 'À nhon !!!',
    introDesc: `Chào mừng bạn đến world cụa tui`,
    btnIntro: 'kekeke',
    title: 'Dô nàh',
    desc: 'Bặn có bị khùm hongg =)))',
    btnYes: 'Cóa, tui khùm nhắm ;)))',
    btnNo: 'Khồng, tui bình thường heheh',
    question:'Lói cho bặn bíc là bặn đẹp trai nhắm đók =)))',
    btnReply: 'Cóa gì muốn lói hơm',
    reply: '나는 당신이 조금 좋아',
    mess: '!ln^n (đố bặn dịch đựt đók </3)',
    messDesc: 'còn mấy môn thi tốt nhaaaaa',
    btnAccept: 'okieee',
    messLink: 'https://www.facebook.com/messages/t/100055148074199/'
